{
  ...
}:
{
  imports = [
    ./btop.nix
    ./direnv.nix
    ./fastfetch.nix
    ./helix.nix
    ./htop.nix
    ./kitty.nix
    ./lazydocker.nix
    ./oh-my-posh.nix
    ./spicetify.nix
    ./vesktop.nix
    ./zed-editor.nix
    ./zen-browser.nix
    ./zsh.nix
    ./yazi.nix
    ./skhd.nix
    ./dank-material-shell.nix
    ./hyprland.nix
    ./leetgpu.nix
    ./git.nix
    ./ssh.nix
    ./rclone.nix
    ./lazygit.nix
    ./mise.nix
    ./claude-code.nix
    ./hyprshot.nix
  ];
}
