# Generated by nixos-generate-config on the target machine.
# Run: sudo nixos-generate-config --show-hardware-config
# Then replace this file with the output.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];
}
